version: "3.9"
services:
  frontend:
    build: .
    container_name: performance-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    # USER already set in image; omit here
    stdin_open: true
    tty: true
    init: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - WATCHPACK_POLLING=true
volumes:
  node_modules:
